# Generated by Django 5.2.7 on 2026-02-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AfricaSight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sight_name', models.CharField(default='unknown', max_length=32, verbose_name='Название')),
                ('sight_country', models.CharField(default='unknown', max_length=32, verbose_name='Место расположения')),
                ('sight_information', models.TextField(default='unknown', max_length=1024, verbose_name='Информация')),
                ('sight_photo', models.ImageField(blank=True, null=True, upload_to='sights/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='AustraliaSight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sight_name', models.CharField(default='unknown', max_length=32, verbose_name='Название')),
                ('sight_country', models.CharField(default='unknown', max_length=32, verbose_name='Место расположения')),
                ('sight_information', models.TextField(default='unknown', max_length=1024, verbose_name='Информация')),
                ('astrl_photo', models.ImageField(blank=True, null=True, upload_to='sights/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTourForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(default='Имя', max_length=32, verbose_name='Ваше имя')),
                ('your_surname', models.CharField(default='Фамилия', max_length=32, verbose_name='Ваша фамилия')),
                ('your_patronimyc', models.CharField(default='Отчество', max_length=32, verbose_name='Ваше отчество')),
                ('hotel_stars', models.CharField(choices=[('2*', '2*'), ('3*', '3*'), ('4*', '4*'), ('5*', '5*')], default='Количество звёзд', max_length=10, verbose_name='Количество звёзд')),
                ('wished_country_for_visiting', models.CharField(choices=[('Франция', 'Франция'), ('Объединенные Арабские Эмираты', 'Объединенные Арабские Эмираты'), ('Таиланд', 'Таиланд'), ('Япония', 'Япония'), ('Турция', 'Турция'), ('Египет', 'Египет'), ('Великобритания', 'Великобритания'), ('Германия', 'Германия'), ('Марокко', 'Марокко'), ('Китай', 'Китай')], default='Куда поедите', max_length=32, verbose_name='Куда поедите')),
                ('adult_amount', models.IntegerField(verbose_name='Количество взрослых')),
                ('children_amount', models.IntegerField(verbose_name='Количество детей')),
            ],
        ),
        migrations.CreateModel(
            name='EurasiaSight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sight_name', models.CharField(default='unknown', max_length=32, verbose_name='Название')),
                ('sight_country', models.CharField(default='unknown', max_length=32, verbose_name='Место расположения')),
                ('sight_information', models.TextField(default='unknown', max_length=1024, verbose_name='Информация')),
                ('continent', models.CharField(choices=[('Евразия', 'Евразия'), ('Африка', 'Африка'), ('Северная Америка', 'Северная Америка'), ('Южная Америка', 'Южная Америка'), ('Австралия', 'Австралия'), ('Антарктида', 'Антарктида')], default='unknown', max_length=50)),
                ('euro_photo', models.ImageField(blank=True, null=True, upload_to='sights/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='MyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routes', models.CharField(verbose_name='Названия маршрутов')),
            ],
        ),
        migrations.CreateModel(
            name='NorthAmericaSight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sight_name', models.CharField(default='unknown', max_length=32, verbose_name='Название')),
                ('sight_country', models.CharField(default='unknown', max_length=32, verbose_name='Место расположения')),
                ('sight_information', models.TextField(default='unknown', max_length=1024, verbose_name='Информация')),
                ('n_photo', models.ImageField(blank=True, null=True, upload_to='sights/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='SouthAmericaSight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sight_name', models.CharField(default='unknown', max_length=32, verbose_name='Название')),
                ('sight_country', models.CharField(default='unknown', max_length=32, verbose_name='Место расположения')),
                ('sight_information', models.TextField(default='unknown', max_length=1024, verbose_name='Информация')),
                ('s_photo', models.ImageField(blank=True, null=True, upload_to='sights/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField()),
                ('password', models.CharField()),
            ],
        ),
    ]
