# Generated by Django 5.2.7 on 2025-11-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AfricaSight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sight_name', models.CharField(default='unknown', max_length=32, verbose_name='Название')),
                ('sight_country', models.CharField(default='unknown', max_length=32, verbose_name='Место расположения')),
                ('sight_information', models.TextField(default='unknown', max_length=1024, verbose_name='Информация')),
            ],
        ),
        migrations.CreateModel(
            name='AustraliaSight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sight_name', models.CharField(default='unknown', max_length=32, verbose_name='Название')),
                ('sight_country', models.CharField(default='unknown', max_length=32, verbose_name='Место расположения')),
                ('sight_information', models.TextField(default='unknown', max_length=1024, verbose_name='Информация')),
            ],
        ),
        migrations.CreateModel(
            name='EurasiaSight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sight_name', models.CharField(default='unknown', max_length=32, verbose_name='Название')),
                ('sight_country', models.CharField(default='unknown', max_length=32, verbose_name='Место расположения')),
                ('sight_information', models.TextField(default='unknown', max_length=1024, verbose_name='Информация')),
            ],
        ),
        migrations.CreateModel(
            name='FirstForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(default='unknown', max_length=32, verbose_name='Ваше имя')),
                ('your_surname', models.CharField(default='unknown', max_length=32, verbose_name='Ваша фамилия')),
                ('visited_country', models.CharField(default='unknown', max_length=128, verbose_name='Где вы были')),
                ('seen_sights', models.CharField(default='unknown', max_length=64, verbose_name='Что удивительного увидели')),
                ('experience', models.TextField(default='unknown', max_length=128, verbose_name='Опыт')),
            ],
        ),
        migrations.CreateModel(
            name='NorthAmericaSight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sight_name', models.CharField(default='unknown', max_length=32, verbose_name='Название')),
                ('sight_country', models.CharField(default='unknown', max_length=32, verbose_name='Место расположения')),
                ('sight_information', models.TextField(default='unknown', max_length=1024, verbose_name='Информация')),
            ],
        ),
        migrations.CreateModel(
            name='SouthAmericaSight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sight_name', models.CharField(default='unknown', max_length=32, verbose_name='Название')),
                ('sight_country', models.CharField(default='unknown', max_length=32, verbose_name='Место расположения')),
                ('sight_information', models.TextField(default='unknown', max_length=1024, verbose_name='Информация')),
            ],
        ),
    ]
