# Generated by Django 5.2.7 on 2025-11-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eurasiasight',
            name='continent',
            field=models.CharField(choices=[('Евразия', 'Евразия'), ('Африка', 'Африка'), ('Северная Америка', 'Северная Америка'), ('Южная Америка', 'Южная Америка'), ('Австралия', 'Австралия'), ('Антарктида', 'Антарктида')], default='unknown', max_length=50),
        ),
    ]
