# Generated by Django 5.2.7 on 2025-11-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0002_eurasiasight_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='africasight',
            name='sight_photo',
            field=models.ImageField(blank=True, null=True, upload_to='sights/', verbose_name='Фото'),
        ),
    ]
