# Generated by Django 5.2.7 on 2026-02-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0002_morechina'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreAboutCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sights/', verbose_name='Фото')),
                ('name', models.CharField(default='unknown', max_length=32, verbose_name='Название')),
                ('country', models.CharField(choices=[('Великобритания', 'Великобритания'), ('Германия', 'Германия'), ('Россия', 'Россия'), ('Китай', 'Китай')], default='unknown', max_length=32, verbose_name='Месторасположение')),
                ('information', models.TextField(default='unknown', max_length=500, verbose_name='Информация')),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='MoreChina',
        ),
    ]
