# Generated by Django 5.2.7 on 2026-02-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0003_moreaboutcountry_delete_morechina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sights/', verbose_name='Фото')),
                ('route_name', models.CharField(default='unknown', max_length=32, verbose_name='Название маршрута')),
                ('information', models.TextField(default='unknown', max_length=300, verbose_name='Информация')),
                ('country', models.CharField(default='unknown', max_length=32, verbose_name='Место')),
            ],
        ),
    ]
