# Generated by Django 5.2.7 on 2025-11-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0003_africasight_sight_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='australiasight',
            name='sight_photo',
            field=models.ImageField(blank=True, null=True, upload_to='sights/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='eurasiasight',
            name='sight_photo',
            field=models.ImageField(blank=True, null=True, upload_to='sights/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='northamericasight',
            name='sight_photo',
            field=models.ImageField(blank=True, null=True, upload_to='sights/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='southamericasight',
            name='sight_photo',
            field=models.ImageField(blank=True, null=True, upload_to='sights/', verbose_name='Фото'),
        ),
    ]
