# Generated by Django 5.2.7 on 2025-11-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0004_australiasight_sight_photo_eurasiasight_sight_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='australiasight',
            old_name='sight_photo',
            new_name='astrl_photo',
        ),
        migrations.RenameField(
            model_name='eurasiasight',
            old_name='sight_photo',
            new_name='euro_photo',
        ),
        migrations.RenameField(
            model_name='northamericasight',
            old_name='sight_photo',
            new_name='n_photo',
        ),
        migrations.RenameField(
            model_name='southamericasight',
            old_name='sight_photo',
            new_name='s_photo',
        ),
    ]
