# Generated by Django 5.2.7 on 2026-02-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0004_routes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodInCoiuntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('cafe', 'Кафе'), ('rest', 'Ресторан'), ('fast', 'Фастфуд')], default='unknown', verbose_name='Типы заведения')),
                ('name', models.CharField(default='unknown', verbose_name='Название заведения')),
                ('place', models.CharField(default='unknown', verbose_name='Месторасположение')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sights/', verbose_name='Фото')),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
