# Generated by Django 5.2.7 on 2026-02-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0005_foodincoiuntries'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodincoiuntries',
            name='information',
            field=models.TextField(default='unknown', max_length=500, verbose_name='Информация'),
        ),
    ]
