# Generated by Django 5.2.7 on 2025-12-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0005_rename_sight_photo_australiasight_astrl_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyTourForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(default='Имя', max_length=32, verbose_name='Ваше имя')),
                ('your_surname', models.CharField(default='Фамилия', max_length=32, verbose_name='Ваша фамилия')),
                ('your_patronimyc', models.CharField(default='Отчество', max_length=32, verbose_name='Ваше отчество')),
                ('hotel_stars', models.CharField(choices=[('2*', '2*'), ('3*', '3*'), ('4*', '4*'), ('5*', '5*')], default='Количество звёзд', max_length=10, verbose_name='Количество звёзд')),
                ('wished_country_for_visiting', models.CharField(choices=[('Франция', 'Франция'), ('Объединенные Арабские Эмираты', 'Объединенные Арабские Эмираты'), ('Таиланд', 'Таиланд'), ('Япония', 'Япония'), ('Турция', 'Турция'), ('Египет', 'Египет'), ('Великобритания', 'Великобритания'), ('Германия', 'Германия'), ('Марокко', 'Марокко'), ('Китай', 'Китай')], default='Куда поедите', max_length=32, verbose_name='Куда поедите')),
                ('adult_amount', models.IntegerField(verbose_name='Количество взрослых')),
                ('children_amount', models.IntegerField(verbose_name='Количество детей')),
            ],
        ),
        migrations.AlterField(
            model_name='firstform',
            name='experience',
            field=models.TextField(default='Опыт', max_length=128, verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='firstform',
            name='seen_sights',
            field=models.CharField(default='Что увидели', max_length=64, verbose_name='Что удивительного увидели'),
        ),
        migrations.AlterField(
            model_name='firstform',
            name='visited_country',
            field=models.CharField(default='Посещённая страна', max_length=128, verbose_name='Где вы были'),
        ),
        migrations.AlterField(
            model_name='firstform',
            name='your_name',
            field=models.CharField(default='Имя', max_length=32, verbose_name='Ваше имя'),
        ),
        migrations.AlterField(
            model_name='firstform',
            name='your_surname',
            field=models.CharField(default='Фамилия', max_length=32, verbose_name='Ваша фамилия'),
        ),
    ]
