# Generated by Django 5.2.7 on 2026-02-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0006_foodincoiuntries_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sights/', verbose_name='Фото')),
                ('name', models.CharField(default='unknown', max_length=32, verbose_name='Название')),
                ('information', models.TextField(default='unknown', max_length=500, verbose_name='Информация')),
            ],
        ),
    ]
