# Generated by Django 5.2.7 on 2025-12-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0006_buytourform_alter_firstform_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routes', models.CharField(verbose_name='Названия маршрутов')),
            ],
        ),
    ]
