# Generated by Django 5.2.7 on 2026-02-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0007_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodincoiuntries',
            name='image',
        ),
    ]
