# Generated by Django 5.2.7 on 2026-02-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0008_remove_foodincoiuntries_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodincoiuntries',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sights/', verbose_name='Фото'),
        ),
    ]
