# Generated by Django 5.2.7 on 2026-02-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0009_foodincoiuntries_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sights/', verbose_name='Фото')),
                ('country', models.CharField(default='unknown', max_length=32, verbose_name='Месторасположение')),
                ('name', models.CharField(default='unknown', max_length=32, verbose_name='Название')),
                ('information', models.TextField(default='unknown', max_length=300, verbose_name='Информация')),
                ('rating', models.FloatField()),
            ],
        ),
    ]
