# Generated by Django 5.2.7 on 2026-03-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0010_maincard'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(default='unknown', max_length=32, verbose_name='Ваше имя')),
                ('your_surname', models.CharField(default='unknown', max_length=32, verbose_name='Ваша фамилия')),
                ('visited_country', models.CharField(default='unknown', max_length=128, verbose_name='Где вы были')),
                ('seen_sights', models.CharField(default='unknown', max_length=64, verbose_name='Что удивительного увидели')),
                ('experience', models.CharField(default='unknown', max_length=128, verbose_name='Опыт')),
            ],
        ),
    ]
