# Generated by Django 5.2.6 on 2026-03-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0011_firstform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuyTourForm',
        ),
        migrations.DeleteModel(
            name='FirstForm',
        ),
    ]
